### ISSUE TITLE
Setting readable line length to be biased left by an adjustable amount. 

### ISSUE THREAD

**Issue by RookieRacoon** [drichardson/obsidian-toggle-readable-line-length#13]
Would there be a way to shift the RRL text to be more biased to the left instead of centered? The problem is very minor but it annoys me for some reason that the text is centered in the text box but in relation to my screen it's shifted pretty far to the left. 
Turning off RLL doesn't help because then all the text is a mess.

**Comment by drichardson** [comment]
You might be able to do it with a CSS snippet. https://help.obsidian.md/Extending+Obsidian/CSS+snippets

I'd check the forums for this. The only thing this extension does is toggle the Obsidian setting.
